services:
  - type: cron
    name: broward-lis-pendens-scraper
    env: docker
    schedule: "0 8 * * 0" # Every Sunday at 8 AM UTC (4 AM Toronto EST/EDT)
    dockerfilePath: ./Dockerfile
    region: oregon # Cost-effective region
    plan: starter # Sufficient for cron jobs
    envVars:
      - key: BROWARD_DAYS_BACK
        value: "7"
      - key: BROWARD_BATCH_SIZE
        value: "9"
      - key: BROWARD_HEADLESS
        value: "true"
      - key: BROWARD_MAX_EXECUTION_TIME
        value: "7200" # 2 hours
      - key: BROWARD_MEMORY_CLEANUP_INTERVAL
        value: "300" # 5 minutes
      - key: BROWARD_PLAYWRIGHT_TIMEOUT
        value: "120000" # 2 minutes timeout for page loads
      - key: BROWARD_PAGE_LOAD_DELAY
        value: "5000" # 5 second delay between page loads
      - key: BROWARD_RETRY_DELAY
        value: "15000" # 15 second delay between retries
      - key: RENDER
        value: "true"
      # Optional webhook for notifications
      # - key: BROWARD_WEBHOOK_URL
      #   value: "https://your-webhook-url.com/notify"

      # Optional skip flags for debugging
      # - key: BROWARD_SKIP_SCRAPING
      #   value: "false"
      # - key: BROWARD_SKIP_PROCESSING
      #   value: "false"
      # - key: BROWARD_SKIP_ADDRESS
      #   value: "false"
      # - key: BROWARD_SKIP_PHONE
      #   value: "false"
