services:
  - type: cron
    name: broward-lis-pendens-scraper
    env: docker
    schedule: "0 8 * * 0" # Every Sunday at 8 AM UTC (4 AM Toronto EST/EDT)
    dockerfilePath: ./Dockerfile
    region: oregon # Cost-effective region
    plan: starter # Sufficient for cron jobs
    envVars:
      - key: BROWARD_DAYS_BACK
        value: "7"
      - key: BROWARD_BATCH_SIZE
        value: "9"
      - key: BROWARD_HEADLESS
        value: "true"
      - key: BROWARD_MAX_EXECUTION_TIME
        value: "7200" # 2 hours
      - key: BROWARD_MEMORY_CLEANUP_INTERVAL
        value: "300" # 5 minutes
      - key: BROWARD_PLAYWRIGHT_TIMEOUT
        value: "180000" # 3 minutes timeout for page loads (increased for slow connections)
      - key: BROWARD_PAGE_LOAD_DELAY
        value: "8000" # 8 second delay between page loads (increased for stability)
      - key: BROWARD_RETRY_DELAY
        value: "20000" # 20 second delay between retries (increased)
      - key: BROWARD_CONNECTION_TIMEOUT
        value: "30000" # 30 second connection timeout
      - key: BROWARD_NAVIGATION_TIMEOUT
        value: "180000" # 3 minute navigation timeout
      - key: BROWARD_SELECTOR_TIMEOUT
        value: "10000" # 10 seconds for element selection
      - key: BROWARD_AGREEMENT_TIMEOUT
        value: "15000" # 15 seconds for agreement buttons
      - key: BROWARD_WEBHOOK_TIMEOUT
        value: "30" # 30 seconds for webhook notifications
      - key: RENDER
        value: "true"
      - key: BROWARD_FALLBACK_ON_NETWORK_ERROR
        value: "true" # Skip scraping if network connectivity fails, process existing data instead
      # Optional webhook for notifications
      # - key: BROWARD_WEBHOOK_URL
      #   value: "https://your-webhook-url.com/notify"

      # Optional skip flags for debugging - ENABLED FOR STABILITY
      - key: BROWARD_SKIP_SCRAPING
        value: "false"
      - key: BROWARD_SKIP_PROCESSING
        value: "false"
      - key: BROWARD_SKIP_ADDRESS
        value: "true" # Skip address extraction - too slow for cloud deployment
      - key: BROWARD_SKIP_PHONE
        value: "true" # Skip phone extraction - too slow for cloud deployment

      # Google Sheets Integration - REQUIRED for automation
      - key: GOOGLE_SERVICE_ACCOUNT
        value: '{"type":"service_account","project_id":"search-aopi","private_key_id":"87991385bab5a6404fb2e87318fcc69b9b3bc9a1","private_key":"-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC5P2q34qDrrbuvwI2hJc6BMh/LCFlF2Re0n3sJTVfMnAX0oSjYx05uzPG6MjrfZ0L+Kv6H3ygyOC/r686wKQcTgpUaYn9NzEVzCAljv350AHG24uLoHT42assrracK6Q98RA0dHj/IV+Njak/78hiZP2mJ9vIDywtmr+pYPu8bIisQwFeCsnv33RRekRX87yaNFjCzpSB0U/4XRDryDQqm3o7Vu4Y3K7a7CfiQfIhjNIfrzqiDHW1Mh5wEjMFVCLWl7PLQJPakOHlwDJdYAiXSpe01TwmqHJJrhvS1aVy5pkeO1VaQDLWxQEFcltMsIovWGX6C7s7XRNcTOSMPp6a9AgMBAAECggEAGnLYfMqpqRyT+ILodcKdGksayPU3McbOIKbIfUqCp577JrM/zrueEinGtYvoZe8rXHitAJ828PyesvNm/jXNYda6DRtVC7mHjOXv2UME/fD2S2NXfEZ4lHJo8aKIgAFIibh5mtevyZ3qxE3wf4tQQckQ+3a7lRkPVqj1L4ZEwz29qELWGb2JJsMhFhtvbyLrSHvAW2EPB4eEA1+9j5TSD0tGCAM2T7mlXfaGeR9Wq8FKB4ueumi6FEYnF4YlkG1AkuqIYKcZ1Jut0IOaDnHjTUKAwyagh+G14MPaDH4i+gsIUJ03GOIT0QP22nLBpKB/RfXmsS12ovGpQx83y2i3LQKBgQD/ajN+7jUP/kOOZiv4/R2vwNWQ5Jz2hafXans2xzqElDeWpDLCMgE90XKJjLd1sjQOKkc6MPZ9n9ppztFzsqtKcM7QgpP0hFxlb90weVPWxtZzRiXPMyVsqMQTkr5onFj4Z62dehTrg2CQmkFSgySFYqs0GixFBQIhWerBfnXAawKBgQC5rBAwCBetBup7u0KgOchei+4V/zM3S3zABri9RVKvG8f0rwYy4aCiWFEwzz7Muzw75r9DecF5l5qG8z4F6PvpHCLG6w9sAzNe qJ/VIEouWQ0BrDPTOXuSlSkuOWXw2pKZqWXWFXh+4ldO90/kNbJhN1hirLdFfoiGXvr3GGrfdwKBgDfdBJJYi2aKGECG/EsjIWEVbiCYv/PzW7hz46shfB0PRfE+zJNI2JiqvMB09JNbfKM0gAusNd1YHy9ROuJxS6GmdrWIOdAbOxI8m0ZE4x9wserYhuCAsUjIyMn3KIo82ADMvF5bG0Q/odk+w9bGNDCwWf21U8VsyQB+aCgV/q8tAoGBAIwWdVQ4Ftz2td5LKHbJghNL0oQIO3VB4ErmB2bOshbqiBBmKfAj6lXy+rcv9rrznfu4GqDncYGzT+T4C9jbs41rLBYXblhZhd2qroVYSn/zsmuLqMJ6wXCUWDDHH9H8p9WGSQ6gvnxFfAhZco7FsOPGpUo19EVbtdhkO0hJxQD7AoGADrslCb3FsJJMwYvSA/3pp4FOsXDdnVpW2cxn1EF2FIvXJ+Fs0IXBUYKgyEFI1GprhQWksroEc01eWBqM25wUDoL8D3QToIVDStbXZpevhtEHF1QMDtp4IEN1l3/6hndiA1cZEpoJCPOLgf25jJChJux6EMQjXFrcOMEw9dqp4cs=\n-----END PRIVATE KEY-----\n","client_email":"broward-sheets-uploader@search-aopi.iam.gserviceaccount.com","client_id":"110499602406925293871","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_x509_cert_url":"https://www.googleapis.com/robot/v1/metadata/x509/broward-sheets-uploader%40search-aopi.iam.gserviceaccount.com","universe_domain":"googleapis.com"}'
      - key: GOOGLE_SHEETS_ID
        value: "1hcUnRsGfk-lraCrRZYJeeBk1QzszoEEZYPdJn9H21tg"
      - key: GOOGLE_SHEETS_SHARE_EMAIL
        value: "sepiboymonster@gmail.com,blakejackson1@gmail.com"
      - key: GOOGLE_SHEETS_WORKSHEET_NAME
        value: "Broward Lis Pendens"
      - key: GOOGLE_SHEETS_APPEND_MODE
        value: "true"

      # Email Notifications - CONFIGURE WITH YOUR GMAIL CREDENTIALS
      # IMPORTANT: Use Gmail App Password, not regular password
      # - key: EMAIL_SMTP_SERVER
      #   value: "smtp.gmail.com"
      # - key: EMAIL_SMTP_PORT
      #   value: "587"
      # - key: EMAIL_USERNAME
      #   value: "your-email@gmail.com"
      # - key: EMAIL_PASSWORD
      #   value: "your-app-password"  # Generate this in Gmail settings
      # - key: EMAIL_FROM
      #   value: "your-email@gmail.com"
      # - key: EMAIL_TO
      #   value: "sepiboymonster@gmail.com,blakejackson1@gmail.com"
      # - key: EMAIL_ENABLED
      #   value: "true"
